[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Configuration du site avec nom personnalisé
[site]
  name = "superapprenant-ci"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration pour le nom de domaine personnalisé
# Décommentez et modifiez si vous avez un domaine personnalisé
# [[redirects]]
#   from = "https://votre-domaine.com/*"
#   to = "https://superapprenant-ci.netlify.app/:splat"
#   status = 301
#   force = true